version: 4
parser:
  git:
    clone: https://github.com/b0o/tree-sitter-cython
    commit: 62f44f5e7e41dde03c5f0a05f035e293bcf2bcf8
    subdirectory: src
extends: Python
definition_query: |
  [
    (class_definition name: (_) @name)
    (function_definition name: (_) @name)
    (decorated_definition
      [ (class_definition name: (_) @name)
        (function_definition name: (_) @name) ])
    (assignment left:
      [ (_) @name
        (attribute attribute: (_) @name)
        (subscript subscript: (string (string_content) @name))
        (pattern_list (identifier) @name) ])
    (global_statement (identifier) @name)
    (nonlocal_statement (identifier) @name)
    (aliased_import alias: (identifier) @name)
    (as_pattern_target (identifier) @name)
  ] @def
  (dictionary (pair key: (string (string_content) @name)) @def)
  (parameters (identifier) @name @def)
  (lambda_parameters (identifier) @name @def)
  (typed_parameter . (identifier) @name) @def
  (default_parameter name: (_) @name) @def
  (typed_default_parameter name: (_) @name) @def
  (for_from_loop left: (_) @name) @def
  (for_in_loop left: [
    (_) @name
    (pattern_list (identifier) @name)]) @def
  (for_in_clause left: [
    (_) @name
    (pattern_list (identifier) @name)]) @def
  (call function: (identifier) @f (#eq? @f "setattr") arguments: (argument_list ("(" (_) "," (string (string_content) @name)))) @def
  (call function: (attribute attribute: (identifier) @f (#any-of? @f "__setattr__" "__setitem__")) arguments: (argument_list ((string (string_content) @name) "," (_) ")"))) @def
  (DEF_statement name: (_) @name) @def
  (cvar_def (maybe_typed_name name: (_) @name)) @def
  (c_parameters (maybe_typed_name name: (_) @name)) @def
  (cvar_decl (identifier) @name) @def
  (cppclass (identifier) @name) @def
  (enum (identifier) @name) @def
  (fused (identifier) @name) @def
  (struct (identifier) @name) @def
  (property_definition (identifier) @name) @def
parent_query: |
  ...
  (cppclass (_) @exclude)
  (enum (block) @exclude)
  (struct (struct_suite) @exclude)
  (property_definition body: (_) @exclude)
