version: 4
parser:
  tarball:
    name: glsl
    sha256hex: 65d098362f9ffd47e9bf5916133ed24ccf934b01027debdaeeb46ff3ec41caf0
    subdirectory: tree-sitter-glsl-0.2.0/src
    url: https://github.com/tree-sitter-grammars/tree-sitter-glsl/archive/refs/tags/v0.2.0.tar.gz
extends: C
