version: 4
parser:
  tarball:
    name: javascript
    sha256hex: fc5b8f5a491a6db33ca4854b044b89363ff7615f4291977467f52c1b92a0c032
    subdirectory: tree-sitter-javascript-0.23.1/src
    url: https://github.com/tree-sitter/tree-sitter-javascript/archive/refs/tags/v0.23.1.tar.gz
definition_query: |
  [
    (function_declaration name: (_) @name)
    (function_expression name: (_) @name)
    (method_definition name: (_) @name)
    (formal_parameters [
      (identifier) @name
      (assignment_pattern left: (identifier) @name)
      (rest_pattern (identifier) @name)])
    (variable_declarator name: (_) @name)
    (array_pattern (identifier) @name)
    (pair_pattern value: (identifier) @name)
    (shorthand_property_identifier_pattern) @name
    (assignment_expression left: [
      (_) @name
      (member_expression property: (_) @name)
      (member_expression object: (_) @name property: ((property_identifier) @prototype (#eq? @prototype "prototype")))
      (member_expression object: (member_expression object: (_) @name property: ((property_identifier) @prototype (#eq? @prototype "prototype"))))])
    (pair key: [
      (property_identifier) @name
      (string (string_fragment) @name)])
    (class_declaration name: (_) @name)
    (field_definition property: (_) @name)
  ] @def
sibling_node_types:
- comment
parent_query: |
  (function_declaration body: (_) @exclude)
  (function_expression body: (_) @exclude)
  (method_definition body: (_) @exclude)
  (arrow_function body: (_) @exclude)
  (class_declaration body: (_) @exclude)
  (variable_declarator value: (_) @exclude)
  (assignment_expression right: (_) @exclude)
