version: 4
parser:
  tarball:
    name: markdown
    sha256hex: e0fdb2dca1eb3063940122e1475c9c2b069062a638c95939e374c5427eddee9f
    subdirectory: tree-sitter-markdown-0.4.1/tree-sitter-markdown/src
    url: https://github.com/tree-sitter-grammars/tree-sitter-markdown/archive/refs/tags/v0.4.1.tar.gz
definition_query: |
  (section [
    (atx_heading heading_content: (_) @name)
    (setext_heading heading_content: (paragraph (inline) @name))]) @def
parent_query: |
  (section . (_) . (_) @exclude)
  (fenced_code_block (code_fence_content) @exclude)
injection_query: |
  (fenced_code_block
    (info_string (language) @lang)
    (code_fence_content) @injection.content
    (#set! injection.language @lang))
  (fenced_code_block
    (fenced_code_block_delimiter) . (block_continuation)
    (code_fence_content) @injection.content)
  (minus_metadata
    (#set! injection.language "YAML")) @injection.content
