version: 4
parser:
  tarball:
    name: latex
    sha256hex: 12223f7cde2fd96c1977ed5266ac932c10c13154f2930363c6e85d7bcd2d3f12
    subdirectory: tree-sitter-latex-0.4.0/src
    url: https://github.com/latex-lsp/tree-sitter-latex/archive/refs/tags/v0.4.0.tar.gz
definition_query: |
  (acronym_definition name: (curly_group_text text: (_) @name)) @def
  (environment_definition name: (curly_group_text text: (_) @name)) @def
  (glossary_entry_definition name: (curly_group_text text: (_) @name)) @def
  (label_definition name: (curly_group_text text: (_) @name)) @def
  (label_number name: (curly_group_text text: (_) @name)) @def
  (new_command_definition declaration:
    [ (curly_group_command_name command: (_) @name)
      (command_name) @name]) @def
  (theorem_definition name: (curly_group_text text: (_) @name)) @def
  (part text: (curly_group (text) @name)) @def
  (chapter text: (curly_group (text) @name)) @def
  (section text: (curly_group (text) @name)) @def
  (subsection text: (curly_group (text) @name)) @def
  (subsubsection text: (curly_group (text) @name)) @def
  (paragraph text: (curly_group (text) @name)) @def
  (part (label_definition name: (curly_group_text text: (_) @name))) @def
  (chapter (label_definition name: (curly_group_text text: (_) @name))) @def
  (section (label_definition name: (curly_group_text text: (_) @name))) @def
  (subsection (label_definition name: (curly_group_text text: (_) @name))) @def
  (subsubsection (label_definition name: (curly_group_text text: (_) @name))) @def
  (paragraph (label_definition name: (curly_group_text text: (_) @name))) @def
  (generic_environment (label_definition name: (curly_group_text text: (_) @name))) @def
parent_query: |
  (part text: (_) . (_) @exclude)
  (chapter text: (_) . (_) @exclude)
  (section text: (_) . (_) @exclude)
  (subsection text: (_) . (_) @exclude)
  (subsubsection text: (_) . (_) @exclude)
  (paragraph text: (_) . (_) @exclude)
  (generic_environment (_) @exclude)
sibling_node_types:
  - line_comment
  - block_comment
